### PR TITLE
Add completions for a handful of units

### PR DESCRIPTION
**Pull request by vrugtehagel**
Related issue: https://github.com/ryboe/CSS3/issues/184

This is a followup to https://github.com/ryboe/CSS3/pull/188.

It adds completions for a handful of missing units; the container query ones, but also a few others that seemed to be missing.

I'm not actually sure these are working (it doesn't seem to, even some of the ones already in this list). Please test before merge, let me know if there's another place I need to update.

### CODE REVIEW

**Comment by argyleink** [comment]
confirm i get syntax highlighting but no autocomplete

**Comment by vrugtehagel** [comment]
Gotcha, I'll tinker a bit more with this later

**Comment by vrugtehagel** [comment]
Actually, it also seems to be lacking for existing units, I don't even get autocomplete for `px`. It does suggest previously used _combinations_, e.g. it will suggest `10px` after writing `10p` if I already declared another `10px` somewhere, but it will not suggest it for new values; I get no suggestions for e.g. `381207p`.

Also, I've added these units to the `"attr"` function which is most definitely wrong. The autocomplete here seems to completely depend on what you've already written:

image

I'm guessing I'm missing something (I might have "proper" autocomplete disabled or something) but let me know what you see on your side.

**Comment by argyleink** [comment]
I can't seem to get completions to work (i also turned them off a long time ago 😬 ). but after enabling them and ensuring i've got all the proper flags enabled, I see this when trying to prompt completions:

Screenshot 2023-08-01 at 3 58 08 PM

I've created #198 so we can merge this and fix this new issue at another time.

**Review by argyleink — APPROVED** [review]

**Pull request merged**
