### PR TITLE
Fix syntax for font shorthand

### PR DESCRIPTION
**Pull request by vrugtehagel**
Related issue: https://github.com/ryboe/CSS3/issues/181

Fixes the `font` shorthand. `font-family-name` was just eating all of the tokens as if they were identifiers, so simply reordering the includes fixes the issue.

### CODE REVIEW

**Comment by vrugtehagel** [comment]
This PR is not quite working:

image

Specifically, 
```css
* {
  /* ... */
  font: large menu;   /* menu is highlighted like an ident. this is correct */
  /* ... */
}
```
is not quite working. What can I do about this?

**Comment by argyleink** [comment]
> What can I do about this?

hm, not sure. I see `menu` [here](https://github.com/ryboe/CSS3/blob/master/completions/properties.py#L972) but not sure how to patch the parsing logic for this case. Maybe @ryboe can help guide us?

**Comment by argyleink** [comment]
not sure we'll get resolution on the ordering issue, so this can exit draft imo

**Comment by ryboe** [comment]
First, I just want to say thanks very much @vrugtehagel for your contributions and @argyleink for reviewing! 🙇 

I'm not sure what's causing the issue, but here's what [Scope Hunter](https://packagecontrol.io/packages/ScopeHunter) shows me.

image

**Comment by vrugtehagel** [comment]
What I think is happening, is that definitions inside `push:` are checked for each token in the order specified. I also fixed this issue under that assumption; if `font-family-name` comes first (which is defined to consume `string`s and `identifier`s) then all tokens will be consumed as such, since most of the tokens match that definition. If we swap `font-family-name` to the end of the list of token definitions, it would try to match these only if no earlier definition matched.

If this is how it works (and I am honestly not sure, but it seems plausible), then it means we cannot differentiate tokens based on their position in the value. So, we can just leave this as-is and just hope not many people call their font-family `menu`.

We _could_ (I think) make an in-value scoping mechanism that switches over to `font-family` identifiers once `font-size` and `line-height` have been parsed, but this seems rather complex. It's a bit out-of-scope, anyway; this PR is an improvement by itself, even with a known minor bug. I say; let's review this as-is, with the bug in mind, and if anyone feels strongly about fixing the issue with the `menu` token then they may open a new issue.

**Review by argyleink — APPROVED** [review]

**Pull request merged**
